// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}
//         <Navbar></Navbar>
//       </body>
//     </html>
//   );
// }



import './globals.css'; 

import Navbar from '../components/Navbar'
// import Footer from '../components/Footer'
import HeroBanner from '../components/HeroBanner'
import Footer from '@/components/Footer';


// import HeroBanner from '@/components/HeroBanner';
// import Footer from '@/components/Footer';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        <main>
          {children}
          <Footer/>
        </main>
      
      
      </body>
    </html>
  )
}